server:
  port: 8080

spring:
  application:
    name: summer24
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/summer24?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: daer8866

id-generator:
  worker-id: 1
